server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/h2/my-store
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
